# Docker Compose
# https://docs.docker.com/compose/

version: '3'
services:

  app:
    image: chatserver-app-dev:0.0.0
    environment: &environment
      - ENVIRONMENT=local
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
      args:
        env: dev
        version: 0.0.0

  check:
    image: chatserver-check-dev:0.0.0
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        env: dev
        version: 0.0.0
    volumes:
      - .:/go/src/github.com/luismayta/chatserver
    env_file:
      - .env
